export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART_BY_ID = "REMOVE_FROM_CART";
export const EMPTY_CART = "CART_EMPTY";
export const CHANGE_CART_ITEM_QUANTITY = "CHANGE_CART_ITEM_QUANTITY";
export const GET_ALL_CART_ITEMS = "GET_ALL_CART_ITEMS";
