export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

export const GET_ALL_FILTERS_REQUEST = "GET_ALL_FILTERS_REQUEST";
export const GET_ALL_FILTERS_SUCCESS = "GET_ALL_FILTERS_SUCCESS";
export const GET_ALL_FILTERS_FAIL = "GET_ALL_FILTERS_FAIL";
export const CHANGE_FILTER_CHECKED_STATE = "CHANGE_FILTER_CHECKED_STATE";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

export const GET_PRODUCT_BY_NAME_REQUEST = "GET_PRODUCT_BY_NAME_REQUEST";
export const GET_PRODUCT_BY_NAME_SUCCESS = "GET_PRODUCT_BY_NAME_SUCCESS";
export const GET_PRODUCT_BY_NAME_FAIL = "GET_PRODUCT_BY_NAME_FAIL";

export const GET_PRODUCTS_BY_MULTY_FILTER_REQUEST =
  "GET_PRODUCTS_BY_MULTY_FILTER_REQUEST";
export const GET_PRODUCTS_BY_MULTY_FILTER_SUCCESS =
  "GET_PRODUCTS_BY_MULTY_FILTER_SUCCESS";
export const GET_PRODUCTS_BY_MULTY_FILTER_FAIL =
  "GET_PRODUCTS_BY_MULTY_FILTER_REQUESTFAIL";

export const GET_SORTED_PRODUCTS = "GET_SORTED_PRODUCTS ";
